### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by zakariaGatter** [buffet/rawm#1]
i really want to use your window manager

but can you add a wiki or at least just a rawmrc example ???

**Comment by buffet** [comment]
I'm very sorry to disappoint you, but this isn't really done yet, I should make that more clear.

Also I wanted to complete this in the off-time, not working on the main project (kiwmi), but I kinda started working on that again, so I can't guarantee I will even complete this right now.

If everything goes as planned, I will implement this idea as a frontend for kiwmi, so you can play around with that (when it's done, which can easily take a few more months).

Thanks for your interest though.
